apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: mq-services-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: ahsoka4
    server: https://kubernetes.default.svc
  project: ahsoka4
  source:
    path: lab3-4/services/ibm-mq/overlays
    repoURL: https://github.com/konradgurbiel-uk/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
